version: '3.4'

services:
  ordering.webapi:
    image: orderingwebapi
    build:
      context: .
      dockerfile: Ordering.WebApi\Dockerfile

  mvccore:
    image: ${DOCKER_REGISTRY}mvccore
    build:
      context: .
      dockerfile: ..\MvcCore\Dockerfile

